
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let state={questions:[],idx:0,score:0,selected:new Set(),checked:false,wrong:[],started:0,timer:null,mode:''};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function sample(a,n){return shuffle(a).slice(0,n)}
function show(id){['home','topicSelect','quiz','result','cheats'].forEach(x=>$('#'+x).classList.add('hidden')); $('#'+id).classList.remove('hidden'); if(id==='home') renderStats()}
function renderStats(){const s=store.get('m130stats',{done:0,right:0}); const mistakes=store.get('m130mistakes',[]).length; const pct=s.done?Math.round(s.right/s.done*100):0; $('#statsBox').innerHTML=`<div class="stat"><b>${s.done}</b><small>решено</small></div><div class="stat"><b>${pct}%</b><small>точность</small></div><div class="stat"><b>${mistakes}</b><small>ошибок</small></div>`}
function start(mode, qs){state={questions:qs,idx:0,score:0,selected:new Set(),checked:false,wrong:[],started:Date.now(),timer:null,mode}; if(!qs.length){alert('Тут пока нет вопросов.');return} show('quiz'); $('#quizMode').textContent=mode; state.timer=setInterval(renderTimer,1000); renderQuestion()}
function renderTimer(){let sec=Math.floor((Date.now()-state.started)/1000),m=Math.floor(sec/60),s=sec%60; $('#timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderQuestion(){const q=state.questions[state.idx]; state.selected=new Set(); state.checked=false; $('#feedback').classList.add('hidden'); $('#nextBtn').classList.add('hidden'); $('#checkBtn').classList.remove('hidden'); $('#qSubject').textContent=q.subject; $('#qTopic').textContent=q.topic; $('#qCounter').textContent=`${state.idx+1}/${state.questions.length}`; $('#qText').textContent=q.text; $('#multiHint').textContent=q.multi?'Можно выбрать несколько вариантов ответа.':'Один правильный ответ.'; $('#progressBar').style.width=((state.idx)/state.questions.length*100)+'%'; const opts=shuffle(q.options); $('#options').innerHTML=opts.map(o=>`<button class="option" data-letter="${o.letter}"><span class="letter">${o.letter}</span><span>${o.text}</span></button>`).join(''); $$('.option').forEach(btn=>btn.onclick=()=>selectOption(btn,q));}
function selectOption(btn,q){if(state.checked)return; const l=btn.dataset.letter; if(q.multi){state.selected.has(l)?state.selected.delete(l):state.selected.add(l); btn.classList.toggle('selected')} else {state.selected=new Set([l]); $$('.option').forEach(b=>b.classList.remove('selected')); btn.classList.add('selected')}}
function check(){const q=state.questions[state.idx]; if(!state.selected.size){alert('Выбери вариант 😭');return} state.checked=true; const corr=[...q.correct].sort().join(''); const ans=[...state.selected].sort().join(''); const ok=corr===ans; if(ok) state.score++; else state.wrong.push(q.id); const stats=store.get('m130stats',{done:0,right:0}); stats.done++; if(ok)stats.right++; store.set('m130stats',stats); let mistakes=store.get('m130mistakes',[]); if(ok) mistakes=mistakes.filter(id=>id!==q.id); else if(!mistakes.includes(q.id)) mistakes.push(q.id); store.set('m130mistakes',mistakes); $$('.option').forEach(b=>{const l=b.dataset.letter; if(q.correct.includes(l)) b.classList.add('correct'); if(state.selected.has(l)&&!q.correct.includes(l)) b.classList.add('wrong')}); $('#feedback').classList.remove('hidden'); $('#feedback').innerHTML= ok ? '✅ Правильно!' : `❌ Неправильно. Правильный ответ: <b>${corr}</b>`; $('#checkBtn').classList.add('hidden'); $('#nextBtn').classList.remove('hidden')}
function next(){if(state.idx<state.questions.length-1){state.idx++;renderQuestion()}else finish()}
function finish(){clearInterval(state.timer); $('#progressBar').style.width='100%'; show('result'); const total=state.questions.length,pct=Math.round(state.score/total*100); $('#resultTitle').textContent=pct>=80?'Красотка, хороший результат 💅':pct>=60?'Норм, но надо повторить темы':'Надо добить ошибки, но всё реально'; $('#resultStats').innerHTML=`<div class="stats"><div class="stat"><b>${state.score}/${total}</b><small>правильно</small></div><div class="stat"><b>${pct}%</b><small>результат</small></div><div class="stat"><b>${state.wrong.length}</b><small>ошибок в сессии</small></div></div>`;}
function bySubject(sub){return QUESTIONS.filter(q=>q.subject===sub)}
function openTopics(){show('topicSelect'); const groups={}; QUESTIONS.forEach(q=>{groups[q.topic]=(groups[q.topic]||0)+1}); $('#topicsList').innerHTML=Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([t,n])=>`<button class="card topic" data-topic="${t}"><h3>${t}</h3><p>${n} вопросов</p></button>`).join(''); $$('.topic').forEach(b=>b.onclick=()=>start('Тема: '+b.dataset.topic, shuffle(QUESTIONS.filter(q=>q.topic===b.dataset.topic))))}
function startMistakes(){const ids=store.get('m130mistakes',[]); start('Мои ошибки', shuffle(QUESTIONS.filter(q=>ids.includes(q.id))))}
$$('.mode').forEach(b=>b.onclick=()=>{const m=b.dataset.mode; if(m==='exam') start('Экзамен', shuffle([...sample(bySubject('Квалиметрия'),30),...sample(bySubject('Испытания, контроль и безопасность продукции'),20)])); if(m==='quick') start('Быстрый тест', sample(QUESTIONS,10)); if(m==='qual') start('Квалиметрия', shuffle(bySubject('Квалиметрия'))); if(m==='icbp') start('ИКБП', shuffle(bySubject('Испытания, контроль и безопасность продукции'))); if(m==='mistakes') startMistakes(); if(m==='topics') openTopics(); if(m==='cheats') show('cheats');});
$$('.back').forEach(b=>b.onclick=()=>{clearInterval(state.timer);show('home')}); $('#checkBtn').onclick=check; $('#nextBtn').onclick=next; $('#skipBtn').onclick=()=>{state.wrong.push(state.questions[state.idx].id); next()}; $('#reviewWrong').onclick=startMistakes; $('#themeBtn').onclick=()=>{document.body.classList.toggle('dark'); store.set('m130theme',document.body.classList.contains('dark')?'dark':'light')}; if(store.get('m130theme','light')==='dark') document.body.classList.add('dark'); renderStats();
